name: build
on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
      - run: yarn install
      - run: yarn lint
      - run: yarn build
      - run: yarn build-parsers
      - run: yarn test
